FROM alpine:3.16

WORKDIR /root/consumer

RUN apk add --update --no-cache python3 py3-pip

COPY requirements.txt .
COPY consumer.py .

RUN pip3 install -r requirements.txt

CMD [ "python3", "consumer.py" ]
